### ISSUE TITLE
Latency Tester not working in Safari

### ISSUE THREAD

**Issue by MinThaMie** [NullVoxPopuli/latency-tester#1]
This [post](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Web_Audio_API_cross_browser) mentions ways to make it also work in Safari and Firefox. They use an [AudioContext Monkey Patch](https://github.com/cwilso/AudioContext-MonkeyPatch). 

This might also fix your Safari and Firefox issues :)

**Comment by NullVoxPopuli** [comment]
Is this still an issue in 2023? I main firefox these days, and the latency tester works -- safari still isn't cross platform, so I can't test that browser.

**Comment by letsgoawaydev** [comment]
on ios safari it seems to be ok

**Comment by NullVoxPopuli** [comment]
thanks!!
