### ISSUE TITLE
Very large latency can't be detected

### ISSUE THREAD

**Issue by mscuthbert** [NullVoxPopuli/latency-tester#2]
For certain speakers (Airplay 2 on Mac, for instance), the latency can be seconds long.  This means that at the default 120bpm, I'm likely playing against the previous beat or two, but it's just counted as being a little bit off.

**Comment by NullVoxPopuli** [comment]
Does changing the bpm to something lower or higher help? :thinking: I wonder if there is a better technique for measuring latency?

Here is how latency is calculated: https://github.com/NullVoxPopuli/latency-tester/blob/gh-pages/index.html#L140

**Comment by mscuthbert** [comment]
Thanks for the great tool. Adjusting it down helps a bit but at very high latency it has to be so slow that getting the right beat is hard (like 40 or 30 bpm). I've been trying a similar technique on another project and the best tool I could come up with was speaking a repeating pattern like "A B C D" and having the user enter the letter they hear. That way you get 4+ extra levels of beat information since if just when "C" is spoken the user enters "A" you'll know that rather than low latency you actually have very high.

**Comment by NullVoxPopuli** [comment]
I think large latency might be able to be detected now? https://nullvoxpopuli.github.io/latency-tester/

**Comment by mscuthbert** [comment]
Works great -- now it could detect the 3sec delay on my Homepod speakers!  

It does introduce a related problem about autoplay response that I'll put in a separate issue.  

(thanks for introducing me to Starbeam -- hadn't heard of it.  Interesting approach)
