### ISSUE TITLE
Site update completely broke latency values

### ISSUE THREAD

**Issue by CheezusCrisp** [NullVoxPopuli/latency-tester#5]
After the site update I've noticed that I can't measure anything anymore. My friend has tested on his system and have noticed the same thing. The readouts range anywhere from 1700-2500ms now and doesn't appear to be accurate at all. Previously the same headset measured around 23ms and I would definitely be able to tell if it's 2000ms. 
![image](https://github.com/NullVoxPopuli/latency-tester/assets/55898326/28102051-203c-4e87-9fdc-4950115b1cac)

**Comment by NullVoxPopuli** [comment]
Thanks for reporting!

When is your first tap? Is it on the zero of the countdown?

If you try this on your phone, are the results the same?

**Comment by CheezusCrisp** [comment]
I've gone back and done a bit more experimenting. You're right. I usually don't click on zero of the count down and like to listen to the beat for a few seconds first to get the rhythm of it. When I started clicking on the zero the values returned back to normal. 

This still isn't what the behaviour was of the previous site however. But now I'm aware that it adds the additional latency of the seconds I wait before eventually clicking.

**Comment by vajahath** [comment]
Same for me. This issue is real. Showing me a delay of more than 2000 ms which I cannot confirm with real world observations.

**Comment by ineshd** [comment]
Maybe ignore clicks that are more than a beat off and treat the next one as for the current beat? If someone needed to adjust it for extremely high latency, they should be able to increase BPM or disable a feature like this. Right now, missing one beat completely messes up the amount of latency.

EDIT: Apparently this was how it used to work. Oops.

**Comment by NullVoxPopuli** [comment]
That honestly sounds like good strategy. Let's do it!

**Comment by RobMcGee** [comment]
Seeing the same behavior by skipping the first few beats to get the rhythm, confused the shit out of me.

**Comment by NullVoxPopuli** [comment]
This has been resolved -- see explanation: https://github.com/NullVoxPopuli/latency-tester/issues/8#issuecomment-1894677192



Thanks for reporting!!!
