### ISSUE TITLE
Website doesn't work on Firefox

### ISSUE THREAD

**Issue by MaxTheSyntax** [NullVoxPopuli/latency-tester#7]
There's not much I can say. Works on Edge and Chrome but on Firefox it acts as if it didn't detect the click so you can't even start the test.

**Comment by NoelleTGS** [comment]
Experiencing this as well. Was working fine ~48 hours ago.

**Comment by NullVoxPopuli** [comment]
Well that's goofy, there's been no update to the site. What Firefox version do ya'll have?

**Comment by NoelleTGS** [comment]
Sorry for late response, completely forgot to check. I'm using latest version, 121.0.1

**Comment by NoelleTGS** [comment]
Every attempt to load the page will give one of two errors:
`Loading failed for the module with source “https://nullvoxpopuli.github.io/latency-tester/src/main.js”.` is the most common one, but around 10% of the time it'll give a TypeError instead about the `import { reactive } from "@starbeam/js";` line in main.js.

**Comment by NullVoxPopuli** [comment]
Should be fixed now, sorry about that!
