### ISSUE TITLE
Delay doesn't seem to be measured with the average of the last 10 beats 

### ISSUE THREAD

**Issue by Calin65** [NullVoxPopuli/latency-tester#8]
Could you add a feature to start playing the beats before the timer counts down? Would help to get into the rhythm before the measurement is taken, I think that's why my values are messed up.

**Comment by NullVoxPopuli** [comment]
I've added a new metric with an explanation, which should regardless of when you start / what beat you're on, looks like this: 
![image](https://github.com/NullVoxPopuli/latency-tester/assets/199018/7483f9ca-a7fc-431b-b0cd-b1b5e8a595a4)


With this text:
> If you happen to miss the first beat, this tries to calculate what your latency would be. The calculation is [current latency] % [ms between beats]. It's possible for someone's hardware to have latency that extends beyond the duration of a whole beat, so it's hard to know if a person just missed a beat, or if they really did click the moment they heard the first beat.

And if you miss a couple beats (in my case, about 11 beats were missed)

![image](https://github.com/NullVoxPopuli/latency-tester/assets/199018/d3a45d56-724a-41e0-b358-daad312d4f66)
